version: "3"

services:
  nikitoz:
    build: .
    restart: always
    container_name: nikitoz

    volumes:
      - ./:/usr/src/project/

    working_dir: /usr/src/project/

    command: python -m src
